from fastapi import FastAPI
from pydantic import BaseModel
from typing import List
app = FastAPI()

class TextPayload(BaseModel):
    text: str

class ReviewsPayload(BaseModel):
    reviews: List[str]
    prompt: str | None = None

@app.post("/summarize")
async def summarize(payload: TextPayload):
    txt = payload.text or ""
    # naive summary: first 3 sentences
    summary = " ".join(txt.split(".")[:3]) or "Short summary generated by mock LLM."
    return {"summary": summary}

@app.post("/tags")
async def tags(payload: TextPayload):
    txt = (payload.text or "").lower()
    candidates = [
        ("art", ["art", "painting", "sculpture", "design"]),
        ("fiction", ["novel", "story", "fiction", "tale"]),
        ("psychology", ["psychology", "behavior", "mind", "cognitive"]),
        ("ai", ["ai", "artificial intelligence", "machine learning", "neural"]),
        ("self-help", ["self-help", "motivation", "habit", "productivity"]),
        ("philosophy", ["philosophy", "ethics", "metaphysics", "logic"]),
        ("history", ["history", "ancient", "medieval", "revolution"]),
        ("science", ["science", "biology", "chemistry", "physics"]),
        ("technology", ["technology", "software", "computer", "engineering"]),
        ("business", ["business", "startup", "management", "finance"]),
    ]
    tags = [label for label, keywords in candidates if any(k in txt for k in keywords)]
    if not tags:
        tags = ["general"]
    return {"tags": tags}

@app.post("/aggregate")
async def aggregate(payload: ReviewsPayload):
    reviews = payload.reviews
    _prompt = payload.prompt or ""
    # naive sentiment aggregation: count positive words (toy)
    pos = sum(1 for r in reviews if "good" in r.lower() or "love" in r.lower())
    neg = sum(1 for r in reviews if "bad" in r.lower() or "hate" in r.lower())
    analysis = f"Positive mentions: {pos}, Negative mentions: {neg}."
    return {"analysis": analysis}
